; HULK -> LLVM IR  (generated by Albert XD )
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i32 @rand()
declare void @srand(i32)
declare i64 @time(i64*)
declare void @abort()
declare double @llvm.pow.f64(double, double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.fabs.f64(double)
declare double @llvm.floor.f64(double)

@.fmt_int  = private unnamed_addr constant [5 x i8] c"%.0f\00"
@.fmt_num  = private unnamed_addr constant [5 x i8] c"%.6g\00"
@.fmt_str  = private unnamed_addr constant [3 x i8] c"%s\00"
@.fmt_nl   = private unnamed_addr constant [2 x i8] c"\0A\00"
@.true_s   = private unnamed_addr constant [5 x i8] c"true\00"
@.false_s  = private unnamed_addr constant [6 x i8] c"false\00"
@.space_s  = private unnamed_addr constant [2 x i8] c" \00"
@.empty_s  = private unnamed_addr constant [1 x i8] c"\00"
@.vec_open = private unnamed_addr constant [2 x i8] c"[\00"
@.vec_close = private unnamed_addr constant [2 x i8] c"]\00"
@.vec_sep  = private unnamed_addr constant [3 x i8] c", \00"
@.oob_msg  = private unnamed_addr constant [36 x i8] c"Runtime error: index out of bounds\0A\00"
@.rand_seeded = global i1 false
%__Vector = type { i64, double*, double, double }


define i8* @__Vector_new(double* %data, double %length) {
entry:
  %obj = call i8* @malloc(i64 32)
  %ptr = bitcast i8* %obj to %__Vector*
  
  ; Almacenar type_id
  %tid_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 0
  store i64 1, i64* %tid_ptr
  
  ; Almacenar data pointer
  %data_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 1
  store double* %data, double** %data_ptr
  
  ; Almacenar length
  %len_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 2
  store double %length, double* %len_ptr
  
  ; Inicializar index en -1
  %idx_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 3
  store double -1.0, double* %idx_ptr
  
  ret i8* %obj
}

define double @__Vector_size(i8* %self) {
entry:
  %ptr = bitcast i8* %self to %__Vector*
  %len_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 2
  %len = load double, double* %len_ptr
  ret double %len
}

define double @__Vector_next(i8* %self) {
entry:
  %ptr = bitcast i8* %self to %__Vector*
  
  ; Cargar índice actual
  %idx_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 3
  %idx = load double, double* %idx_ptr
  
  ; Incrementar índice
  %next_idx = fadd double %idx, 1.0
  store double %next_idx, double* %idx_ptr
  
  ; Cargar length
  %len_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 2
  %len = load double, double* %len_ptr
  
  ; Comparar: next_idx < len
  %cond = fcmp olt double %next_idx, %len
  %result = select i1 %cond, double 1.0, double 0.0
  ret double %result
}

define double @__Vector_get_current(i8* %self) {
entry:
  %ptr = bitcast i8* %self to %__Vector*
  
  ; Cargar índice actual
  %idx_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 3
  %idx_d = load double, double* %idx_ptr
  %idx = fptosi double %idx_d to i64
  
  ; Cargar data pointer
  %data_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 1
  %data = load double*, double** %data_ptr
  
  ; Acceder al elemento en data[idx]
  %elem_ptr = getelementptr double, double* %data, i64 %idx
  %value = load double, double* %elem_ptr
  ret double %value
}

define double @__hulk_main() {
entry:
  %t0 = call i8* @malloc(i64 40)
  %t1 = bitcast i8* %t0 to double*
  %t2 = getelementptr double, double* %t1, i64 0
  store double 1.0e0, double* %t2
  %t3 = getelementptr double, double* %t1, i64 1
  store double 2.0e0, double* %t3
  %t4 = getelementptr double, double* %t1, i64 2
  store double 3.0e0, double* %t4
  %t5 = getelementptr double, double* %t1, i64 3
  store double 4.0e0, double* %t5
  %t6 = getelementptr double, double* %t1, i64 4
  store double 5.0e0, double* %t6
  %t7 = call i8* @__Vector_new(double* %t1, double 5.0e0)
  %t8 = ptrtoint i8* %t7 to i64
  %t9 = bitcast i64 %t8 to double
  %t10 = alloca double
  store double %t9, double* %t10
  %t11 = load double, double* %t10
  call void @__hulk_print_vector(double %t11)
  %t12 = load double, double* %t10
  %t13 = bitcast double %t12 to i64
  %t14 = alloca i64
  store i64 %t13, i64* %t14
  %t15 = load i64, i64* %t14
  %t16 = inttoptr i64 %t15 to i8*
  %t17 = bitcast i8* %t16 to %__Vector*
  %t18 = getelementptr inbounds %__Vector, %__Vector* %t17, i32 0, i32 2
  %t19 = load double, double* %t18
  %t20 = fptosi double %t19 to i64
  %t21 = fptosi double 0.0e0 to i64
  %t22 = icmp slt i64 %t21, 0
  %t23 = icmp sge i64 %t21, %t20
  %t24 = or i1 %t22, %t23
  br i1 %t24, label %idx_oob_26, label %idx_ok_25
idx_oob_26:
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.oob_msg, i64 0, i64 0))
  call void @abort()
  unreachable
idx_ok_25:
  %t27 = getelementptr inbounds %__Vector, %__Vector* %t17, i32 0, i32 1
  %t28 = load double*, double** %t27
  %t29 = getelementptr double, double* %t28, i64 %t21
  %t30 = load double, double* %t29
  call void @__hulk_print_val(double %t30)
  %t31 = load double, double* %t10
  %t32 = bitcast double %t31 to i64
  %t33 = alloca i64
  store i64 %t32, i64* %t33
  %t34 = load i64, i64* %t33
  %t35 = inttoptr i64 %t34 to i8*
  %t36 = bitcast i8* %t35 to %__Vector*
  %t37 = getelementptr inbounds %__Vector, %__Vector* %t36, i32 0, i32 2
  %t38 = load double, double* %t37
  %t39 = fptosi double %t38 to i64
  %t40 = fptosi double 4.0e0 to i64
  %t41 = icmp slt i64 %t40, 0
  %t42 = icmp sge i64 %t40, %t39
  %t43 = or i1 %t41, %t42
  br i1 %t43, label %idx_oob_45, label %idx_ok_44
idx_oob_45:
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.oob_msg, i64 0, i64 0))
  call void @abort()
  unreachable
idx_ok_44:
  %t46 = getelementptr inbounds %__Vector, %__Vector* %t36, i32 0, i32 1
  %t47 = load double*, double** %t46
  %t48 = getelementptr double, double* %t47, i64 %t40
  %t49 = load double, double* %t48
  call void @__hulk_print_val(double %t49)
  %t50 = call i8* @malloc(i64 80)
  %t51 = bitcast i8* %t50 to double*
  %t52 = getelementptr double, double* %t51, i64 0
  store double 1.0e0, double* %t52
  %t53 = getelementptr double, double* %t51, i64 1
  store double 2.0e0, double* %t53
  %t54 = getelementptr double, double* %t51, i64 2
  store double 3.0e0, double* %t54
  %t55 = getelementptr double, double* %t51, i64 3
  store double 4.0e0, double* %t55
  %t56 = getelementptr double, double* %t51, i64 4
  store double 5.0e0, double* %t56
  %t57 = getelementptr double, double* %t51, i64 5
  store double 6.0e0, double* %t57
  %t58 = getelementptr double, double* %t51, i64 6
  store double 7.0e0, double* %t58
  %t59 = getelementptr double, double* %t51, i64 7
  store double 8.0e0, double* %t59
  %t60 = getelementptr double, double* %t51, i64 8
  store double 9.0e0, double* %t60
  %t61 = getelementptr double, double* %t51, i64 9
  store double 1.0e1, double* %t61
  %t62 = call i8* @__Vector_new(double* %t51, double 1.0e1)
  %t63 = ptrtoint i8* %t62 to i64
  %t64 = bitcast i64 %t63 to double
  %t65 = alloca double
  store double %t64, double* %t65
  %t66 = load double, double* %t65
  %t67 = bitcast double %t66 to i64
  %t68 = alloca i64
  store i64 %t67, i64* %t68
  %t69 = load i64, i64* %t68
  %t70 = inttoptr i64 %t69 to i8*
  %t71 = mul i64 101, 8
  %t72 = call i8* @malloc(i64 %t71)
  %t73 = bitcast i8* %t72 to double*
  %t74 = alloca i64
  store i64 0, i64* %t74
  %t75 = alloca i64
  store i64 100, i64* %t75
  %t76 = alloca double*
  store double* %t73, double** %t76
  br label %vgc_77
vgc_77:
  %t80 = call double @__Vector_next(i8* %t70)
  %t81 = fcmp one double %t80, 0.0
  br i1 %t81, label %vgb_78, label %vge_79
vgb_78:
  %t82 = call double @__Vector_get_current(i8* %t70)
  %t83 = alloca double
  store double %t82, double* %t83
  %t84 = load double, double* %t83
  %t85 = load double, double* %t83
  %t86 = fmul double %t84, %t85
  %t87 = load i64, i64* %t74
  %t88 = load i64, i64* %t75
  %t89 = icmp sge i64 %t87, %t88
  br i1 %t89, label %vg_grow_90, label %vg_store_91
vg_grow_90:
  %t92 = mul i64 %t88, 2
  %t93 = add i64 %t92, 1
  %t94 = mul i64 %t93, 8
  %t95 = load double*, double** %t76
  %t96 = bitcast double* %t95 to i8*
  %t97 = call i8* @realloc(i8* %t96, i64 %t94)
  %t98 = bitcast i8* %t97 to double*
  store double* %t98, double** %t76
  store i64 %t92, i64* %t75
  br label %vg_store_91
vg_store_91:
  %t99 = load double*, double** %t76
  %t100 = add i64 %t87, 1
  %t101 = getelementptr double, double* %t99, i64 %t100
  store double %t86, double* %t101
  %t102 = add i64 %t87, 1
  store i64 %t102, i64* %t74
  br label %vgc_77
vge_79:
  %t103 = load i64, i64* %t74
  %t104 = sitofp i64 %t103 to double
  %t105 = load double*, double** %t76
  %t106 = call i8* @__Vector_new(double* %t105, double %t104)
  %t107 = ptrtoint i8* %t106 to i64
  %t108 = bitcast i64 %t107 to double
  %t109 = alloca double
  store double %t108, double* %t109
  %t110 = load double, double* %t109
  call void @__hulk_print_vector(double %t110)
  %t111 = load double, double* %t109
  %t112 = bitcast double %t111 to i64
  %t113 = alloca i64
  store i64 %t112, i64* %t113
  %t114 = load i64, i64* %t113
  %t115 = inttoptr i64 %t114 to i8*
  %t116 = bitcast i8* %t115 to %__Vector*
  %t117 = getelementptr inbounds %__Vector, %__Vector* %t116, i32 0, i32 2
  %t118 = load double, double* %t117
  %t119 = fptosi double %t118 to i64
  %t120 = fptosi double 5.0e0 to i64
  %t121 = icmp slt i64 %t120, 0
  %t122 = icmp sge i64 %t120, %t119
  %t123 = or i1 %t121, %t122
  br i1 %t123, label %idx_oob_125, label %idx_ok_124
idx_oob_125:
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([36 x i8], [36 x i8]* @.oob_msg, i64 0, i64 0))
  call void @abort()
  unreachable
idx_ok_124:
  %t126 = getelementptr inbounds %__Vector, %__Vector* %t116, i32 0, i32 1
  %t127 = load double*, double** %t126
  %t128 = getelementptr double, double* %t127, i64 %t120
  %t129 = load double, double* %t128
  call void @__hulk_print_val(double %t129)
  %t130 = call i8* @malloc(i64 24)
  %t131 = bitcast i8* %t130 to double*
  %t132 = getelementptr double, double* %t131, i64 0
  store double 1.0e1, double* %t132
  %t133 = getelementptr double, double* %t131, i64 1
  store double 2.0e1, double* %t133
  %t134 = getelementptr double, double* %t131, i64 2
  store double 3.0e1, double* %t134
  %t135 = call i8* @__Vector_new(double* %t131, double 3.0e0)
  %t136 = ptrtoint i8* %t135 to i64
  %t137 = bitcast i64 %t136 to double
  %t138 = alloca double
  store double %t137, double* %t138
  %t139 = load double, double* %t138
  %t140 = bitcast double %t139 to i64
  %t141 = alloca i64
  store i64 %t140, i64* %t141
  %t142 = load i64, i64* %t141
  %t143 = inttoptr i64 %t142 to i8*
  %t144 = mul i64 101, 8
  %t145 = call i8* @malloc(i64 %t144)
  %t146 = bitcast i8* %t145 to double*
  %t147 = alloca i64
  store i64 0, i64* %t147
  %t148 = alloca i64
  store i64 100, i64* %t148
  %t149 = alloca double*
  store double* %t146, double** %t149
  br label %vgc_150
vgc_150:
  %t153 = call double @__Vector_next(i8* %t143)
  %t154 = fcmp one double %t153, 0.0
  br i1 %t154, label %vgb_151, label %vge_152
vgb_151:
  %t155 = call double @__Vector_get_current(i8* %t143)
  %t156 = alloca double
  store double %t155, double* %t156
  %t157 = load double, double* %t156
  %t158 = fmul double %t157, 2.0e0
  %t159 = load i64, i64* %t147
  %t160 = load i64, i64* %t148
  %t161 = icmp sge i64 %t159, %t160
  br i1 %t161, label %vg_grow_162, label %vg_store_163
vg_grow_162:
  %t164 = mul i64 %t160, 2
  %t165 = add i64 %t164, 1
  %t166 = mul i64 %t165, 8
  %t167 = load double*, double** %t149
  %t168 = bitcast double* %t167 to i8*
  %t169 = call i8* @realloc(i8* %t168, i64 %t166)
  %t170 = bitcast i8* %t169 to double*
  store double* %t170, double** %t149
  store i64 %t164, i64* %t148
  br label %vg_store_163
vg_store_163:
  %t171 = load double*, double** %t149
  %t172 = add i64 %t159, 1
  %t173 = getelementptr double, double* %t171, i64 %t172
  store double %t158, double* %t173
  %t174 = add i64 %t159, 1
  store i64 %t174, i64* %t147
  br label %vgc_150
vge_152:
  %t175 = load i64, i64* %t147
  %t176 = sitofp i64 %t175 to double
  %t177 = load double*, double** %t149
  %t178 = call i8* @__Vector_new(double* %t177, double %t176)
  %t179 = ptrtoint i8* %t178 to i64
  %t180 = bitcast i64 %t179 to double
  %t181 = alloca double
  store double %t180, double* %t181
  %t182 = load double, double* %t181
  call void @__hulk_print_vector(double %t182)
  %t183 = call i8* @malloc(i64 0)
  %t184 = bitcast i8* %t183 to double*
  %t185 = call i8* @__Vector_new(double* %t184, double 0.0e0)
  %t186 = ptrtoint i8* %t185 to i64
  %t187 = bitcast i64 %t186 to double
  %t188 = alloca double
  store double %t187, double* %t188
  %t189 = load double, double* %t188
  call void @__hulk_print_vector(double %t189)
  ret double 4.2e1
}

define i8* @__hulk_num_to_str(double %val) {
entry:
  %fl = call double @llvm.floor.f64(double %val)
  %diff = fsub double %val, %fl
  %is_int = fcmp oeq double %diff, 0.0
  %abs_val = call double @llvm.fabs.f64(double %val)
  %small_enough = fcmp olt double %abs_val, 1.0e15
  %use_int = and i1 %is_int, %small_enough
  br i1 %use_int, label %fmt_as_int, label %fmt_as_dbl
fmt_as_int:
  %ilen = call i32 (i8*, i64, i8*, ...) @snprintf(i8* null, i64 0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_int, i64 0, i64 0), double %val)
  %ilen64 = sext i32 %ilen to i64
  %ibufsz = add i64 %ilen64, 1
  %ibuf = call i8* @malloc(i64 %ibufsz)
  call i32 (i8*, i64, i8*, ...) @snprintf(i8* %ibuf, i64 %ibufsz, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_int, i64 0, i64 0), double %val)
  ret i8* %ibuf
fmt_as_dbl:
  %dlen = call i32 (i8*, i64, i8*, ...) @snprintf(i8* null, i64 0, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_num, i64 0, i64 0), double %val)
  %dlen64 = sext i32 %dlen to i64
  %dbufsz = add i64 %dlen64, 1
  %dbuf = call i8* @malloc(i64 %dbufsz)
  call i32 (i8*, i64, i8*, ...) @snprintf(i8* %dbuf, i64 %dbufsz, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_num, i64 0, i64 0), double %val)
  ret i8* %dbuf
}

define i8* @__hulk_bool_to_str(double %val) {
entry:
  %cond = fcmp one double %val, 0.0
  %res = select i1 %cond, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.true_s, i64 0, i64 0), i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.false_s, i64 0, i64 0)
  ret i8* %res
}

define void @__hulk_print_val(double %val) {
entry:
  ; Respaldo: imprimir como número (por defecto seguro para tipo Unknown)
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_num, i64 0, i64 0), double %val)
  call i32 @puts(i8* getelementptr inbounds ([1 x i8], [1 x i8]* @.empty_s, i64 0, i64 0))
  ret void
}

define i8* @__hulk_to_str(double %val) {
entry:
  %numstr = call i8* @__hulk_num_to_str(double %val)
  ret i8* %numstr
}

define void @__hulk_print_vector(double %val) {
entry:
  ; Decodificar objeto Vector
  %pi = bitcast double %val to i64
  %obj_ptr = inttoptr i64 %pi to i8*
  %ptr = bitcast i8* %obj_ptr to %__Vector*
  
  ; Leer longitud del vector
  %len_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 2
  %len_d = load double, double* %len_ptr
  %len_i = fptosi double %len_d to i64
  
  ; Leer data pointer
  %data_ptr_loc = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 1
  %data_ptr = load double*, double** %data_ptr_loc
  
  ; Imprimir apertura
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.vec_open, i64 0, i64 0))
  
  ; Inicializar índice
  %idx_ptr = alloca i64
  store i64 0, i64* %idx_ptr
  br label %loop_cond
  
loop_cond:
  %i = load i64, i64* %idx_ptr
  %cond = icmp slt i64 %i, %len_i
  br i1 %cond, label %loop_body, label %loop_end
  
loop_body:
  ; Leer elemento en posición i
  %elem_ptr = getelementptr double, double* %data_ptr, i64 %i
  %elem = load double, double* %elem_ptr
  
  ; Imprimir separador si no es el primero
  %is_first = icmp eq i64 %i, 0
  br i1 %is_first, label %print_elem, label %print_sep
  
print_sep:
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.vec_sep, i64 0, i64 0))
  br label %print_elem
  
print_elem:
  ; Imprimir el elemento
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.fmt_num, i64 0, i64 0), double %elem)
  
  ; Incrementar índice
  %next_i = add i64 %i, 1
  store i64 %next_i, i64* %idx_ptr
  br label %loop_cond
  
loop_end:
  ; Imprimir cierre
  call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.vec_close, i64 0, i64 0))
  call i32 @puts(i8* getelementptr inbounds ([1 x i8], [1 x i8]* @.empty_s, i64 0, i64 0))
  ret void
}

define i8* @__hulk_vector_to_str(double %val) {
entry:
  ; Decodificar objeto Vector
  %pi = bitcast double %val to i64
  %obj_ptr = inttoptr i64 %pi to i8*
  %ptr = bitcast i8* %obj_ptr to %__Vector*
  
  ; Leer longitud
  %len_ptr = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 2
  %len_d = load double, double* %len_ptr
  %len_i = fptosi double %len_d to i64
  
  ; Leer data pointer
  %data_ptr_loc = getelementptr inbounds %__Vector, %__Vector* %ptr, i32 0, i32 1
  %data_ptr = load double*, double** %data_ptr_loc
  
  ; Calcular tamaño aproximado del buffer (20 chars por número + separadores)
  %est_size = mul i64 %len_i, 20
  %buf_size = add i64 %est_size, 100
  %buf_raw = call i8* @malloc(i64 %buf_size)
  
  ; Copiar '['
  %pos_ptr = alloca i64
  store i64 0, i64* %pos_ptr
  %open_ptr = getelementptr i8, i8* %buf_raw, i64 0
  store i8 91, i8* %open_ptr  ; '[' = 91
  store i64 1, i64* %pos_ptr
  
  ; Loop sobre elementos
  %idx_ptr = alloca i64
  store i64 0, i64* %idx_ptr
  br label %loop_cond
  
loop_cond:
  %i = load i64, i64* %idx_ptr
  %cond = icmp slt i64 %i, %len_i
  br i1 %cond, label %loop_body, label %loop_end
  
loop_body:
  ; Agregar separador si no es el primero
  %is_first = icmp eq i64 %i, 0
  br i1 %is_first, label %get_elem, label %add_sep
  
add_sep:
  %pos1 = load i64, i64* %pos_ptr
  %sep1_ptr = getelementptr i8, i8* %buf_raw, i64 %pos1
  store i8 44, i8* %sep1_ptr  ; ',' = 44
  %pos2 = add i64 %pos1, 1
  %sep2_ptr = getelementptr i8, i8* %buf_raw, i64 %pos2
  store i8 32, i8* %sep2_ptr  ; ' ' = 32
  %pos3 = add i64 %pos2, 1
  store i64 %pos3, i64* %pos_ptr
  br label %get_elem
  
get_elem:
  ; Leer elemento y convertir a string
  %elem_ptr = getelementptr double, double* %data_ptr, i64 %i
  %elem = load double, double* %elem_ptr
  %elem_str = call i8* @__hulk_num_to_str(double %elem)
  
  ; Concatenar al buffer
  %pos4 = load i64, i64* %pos_ptr
  %dest_ptr = getelementptr i8, i8* %buf_raw, i64 %pos4
  call i8* @strcpy(i8* %dest_ptr, i8* %elem_str)
  %elem_len = call i64 @strlen(i8* %elem_str)
  %pos5 = add i64 %pos4, %elem_len
  store i64 %pos5, i64* %pos_ptr
  call void @free(i8* %elem_str)
  
  ; Siguiente
  %next_i = add i64 %i, 1
  store i64 %next_i, i64* %idx_ptr
  br label %loop_cond
  
loop_end:
  ; Agregar ']'
  %pos6 = load i64, i64* %pos_ptr
  %close_ptr = getelementptr i8, i8* %buf_raw, i64 %pos6
  store i8 93, i8* %close_ptr  ; ']' = 93
  %pos7 = add i64 %pos6, 1
  %null_ptr = getelementptr i8, i8* %buf_raw, i64 %pos7
  store i8 0, i8* %null_ptr    ; null terminator
  
  ret i8* %buf_raw
}

define i32 @main() {
entry:
  call double @__hulk_main()
  ret i32 0
}

